//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceMaster
    {
        public int Distance_ID { get; set; }
        public string Location1 { get; set; }
        public string Location2 { get; set; }
        public Nullable<int> Distance { get; set; }
    }
}
