//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public int Vehicle_ID { get; set; }
        public string Vehicle_Type { get; set; }
        public string Vehicle_Model { get; set; }
        public string Vehicle_Number { get; set; }
    }
}
